function crop_tiff_time(pathname,index_range)

%% crop_tiff_time

% Allows user to crops a specific range of frames from a tiff file
% generated by other sheffield functions

% INPUT (optional): 
%   (pathname): full path of tiff file to be cropped. 
%      -if no path is provided, GUI will apear that allows user to choose file 
%      
%   (index_range): a 1X2 vector containing the first and last frame to be
%       cropped (example: [1,1000}
%       -if no range is provided, GUI will apear that allows user to choose
%       range

% OUTPUT
%    (data): the data in a matrix
%       -will also save data in the form of a tiff.  filename will be
%       amended to include '_crop_' and the index range and will be saved
%       in the same directory as the initial tiff.


%%  Inputs
if ~exist('pathname','var')
    [filename, loc] = uigetfile('*.tif','Choose the tiff file you would like to crop');% Select Tif to be cell sorted
    pathname = [loc filename];
end
if exist('index_range','var')
    inputs{1} =num2str(index_range(1));
    inputs{2} =num2str(index_range(2));
else
    prompt = {'First frame', 'Last Frame'};
title = 'Enter the frame range you would like to crop';
dims = [1 10];
definput = {'',''};
AddOpts.Resize='on';
AddOpts.WindowStyle='normal';
AddOpts.Interpreter='tex';
inputs = inputdlgcol(prompt,title,dims,definput,AddOpts,2);
end


%% load and write data into new tiff

data=load_tiffs_fast(pathname,'start_ind',str2double(inputs(1)),'end_ind',str2double(inputs(2)));
write_tiff_fast([pathname(1:end-4) '_crop_z_' inputs{1} '-' inputs{2} '.tif'],data);

disp([pathname(1:end-4) '_crop_z_' inputs{1} '-' inputs{2} '.tif' ' has been saved']);