function crop_tiff_space(pathname)

%% crop_tiff_space

% Allows user to crops a specific area of a tiff file generated by other sheffield functions

% INPUT (optional):
%   (pathname): full path of tiff file to be cropped.
%      -if no path is provided, GUI will apear that allows user to choose file
%
% OUTPUT
%    (Cdata): the data in a matrix % this is no longer the case...only a new
%    file will be saved.  if you wish to use this function to output the
%    data simple change line 1 to: function [Cdata] = crop_tiff_space(pathname)

%       -will also save data in the form of a tiff.  filename will be
%       amended to include '_crop_' and the index range and will be saved
%       in the same directory as the initial tiff.


%%  Inputs
if ~exist('pathname','var')
    [filename, loc] = uigetfile('*.tif','Choose the tiff file you would like to crop');% Select Tif to be cell sorted
    pathname = [loc filename];
end
data=load_tiffs_fast(pathname); %load tiff into data

ctch = 0;
while ctch == 0
    meanImg =  uint16(mean(data,3));
    low = min(min(meanImg));
    high = max(max(meanImg));
    meanDisp = figure;
    imshow(meanImg,[low high]);
    p = ginput(2);
    close (meanDisp)
    sp = zeros(1,4);
    sp(1) = min(floor(p(1)), floor(p(2))); %xmin
    sp(2) = min(floor(p(3)), floor(p(4))); %ymin
    sp(3) = max(ceil(p(1)), ceil(p(2)));   %xmax
    sp(4) = max(ceil(p(3)), ceil(p(4)));   %ymax
    
    if sp(1)<=0
        sp(1)=1;
    end
    
    if sp(2)<=0
        sp(2)=1;
    end
    
    if sp(3)>size(data,2)
        sp(3)=size(data,2);
    end
    
    if sp(4)>size(data,1)
        sp(4)=size(data,1);
    end
    
    
    Cdata = data(sp(2):sp(4), sp(1): sp(3),:);
    
    CImg =  uint16(mean(Cdata,3));
    low = min(min(CImg));
    high = max(max(CImg));
    CDisp = figure;
    imshow(CImg,[low high]);
    
    like = input('Do you like this cropped image? (y/n) >> ','s');
    
    if any(ismember(like,'y'))==1 || any(ismember(like,'Y'))==1
        close(CDisp)
        ctch = 1;
    else
        close(CDisp)
        ctch = 0;
    end
end
    
%% write data into new tiff


write_tiff_fast([pathname(1:end-4) '_2Dcrop_' num2str(sp(1)) '_' num2str(sp(2)) ' - ' num2str(sp(3)) '_' num2str(sp(4)) '.tif'],Cdata);

disp([pathname(1:end-4) '_2Dcrop_' num2str(sp(1)) '_' num2str(sp(2)) ' - ' num2str(sp(3)) '_' num2str(sp(4)) '.tif' ' has been saved']);