function [Corrpeak]=CorrOKANpeak(VelGOF)
for i=1:length(fieldnames(VelGOF))
    Fname=fieldnames(VelGOF);
    Corrpeak.Duration(1,i)=str2num(Fname{i}(6:end));
    EstimatAdapt(1,i)=VelGOF.merge40.OKNL(5*60)-VelGOF.merge40.OKNL((Corrpeak.Duration(1,i)+5)*60);
    EstimatAdapt(2,i)=VelGOF.merge40.OKNR(5*60)-VelGOF.merge40.OKNR((Corrpeak.Duration(1,i)+5)*60);
    
    Corrpeak.OKANL_peak(:,i)=VelGOF.(Fname{i}).PeakVelL;
    Corrpeak.OKANR_peak(:,i)=VelGOF.(Fname{i}).PeakVelR;
end
hold off
% peak correlate to time
% [Corrpeak.rho_pval_l(1),Corrpeak.rho_pval_l(2)] = corr(Corrpeak.Duration',Corrpeak.OKANL_peak(2,:)');
% [Corrpeak.rho_pval_r(1),Corrpeak.rho_pval_r(2)] = corr(Corrpeak.Duration',Corrpeak.OKANR_peak(2,:)');
% 
% plot(Corrpeak.Duration,Corrpeak.OKANL_peak(2,:),'o',...
%     'MarkerEdgeColor','b',...
%     'MarkerSize',15,...
%     'LineWidth',2.5);
% 
% hold on
% plot(Corrpeak.Duration,Corrpeak.OKANR_peak(2,:),'o',...
%     'MarkerEdgeColor','r',...
%     'MarkerSize',15,...
%     'LineWidth',2.5);

%peak correlate to estimate OKN adaptation
[Corrpeak.meanrho_pval_l(1),Corrpeak.meanrho_pval_l(2)] = corr(EstimatAdapt(1,:)',abs(Corrpeak.OKANL_peak(2,:))');
[Corrpeak.meanrho_pval_r(1),Corrpeak.meanrho_pval_r(2)] = corr(EstimatAdapt(2,:)',abs(Corrpeak.OKANR_peak(2,:))');

plot(EstimatAdapt(1,:),abs(Corrpeak.OKANL_peak(2,:)),'o',...
    'MarkerEdgeColor','b',...
    'MarkerSize',10,...
    'LineWidth',2.5);

hold on
plot(EstimatAdapt(2,:),abs(Corrpeak.OKANR_peak(2,:)),'o',...
    'MarkerEdgeColor','r',...
    'MarkerSize',10,...
    'LineWidth',2.5);


% peak correlate to time exclude 40 min
% [Corrpeak.rho_pval_l(1),Corrpeak.rho_pval_l(2)] = corr(Corrpeak.Duration(2:5)',Corrpeak.OKANL_peak(2,2:5)');
% [Corrpeak.rho_pval_r(1),Corrpeak.rho_pval_r(2)] = corr(Corrpeak.Duration(2:5)',Corrpeak.OKANR_peak(2,2:5)');
% 
% plot(Corrpeak.Duration,Corrpeak.OKANL_peak(2,:),'o',...
%     'MarkerEdgeColor','b',...
%     'MarkerSize',15,...
%     'LineWidth',2.5);
% 
% hold on
% plot(Corrpeak.Duration,Corrpeak.OKANR_peak(2,:),'o',...
%     'MarkerEdgeColor','r',...
%     'MarkerSize',15,...
%     'LineWidth',2.5);


%peak correlate to OKN adaptation
% [Corrpeak.rho_pval_l(1),Corrpeak.rho_pval_l(2)] = corr(Corrpeak.OKANL_peak(1,:)',Corrpeak.OKANL_peak(2,:)');
% [Corrpeak.rho_pval_r(1),Corrpeak.rho_pval_r(2)] = corr(Corrpeak.OKANR_peak(1,:)',Corrpeak.OKANR_peak(2,:)');
% 
% plot(Corrpeak.OKANL_peak(1,:),Corrpeak.OKANL_peak(2,:),'o',...
%     'MarkerEdgeColor','b',...
%     'MarkerSize',15,...
%     'LineWidth',2.5);
% 
% hold on
% plot(Corrpeak.OKANR_peak(1,:),Corrpeak.OKANR_peak(2,:),'o',...
%     'MarkerEdgeColor','r',...
%     'MarkerSize',15,...
%     'LineWidth',2.5);

%peak correlate to estimate OKN adaptation
% EstimatAdapt=VelGOF.merge40.OKNL(5*60)-VelGOF.merge20.OKNL((Corrpeak.Duration+5)*60);
% 
% [Corrpeak.rho_pval_l(1),Corrpeak.rho_pval_l(2)] = corr(EstimatAdapt,Corrpeak.OKANL_peak(2,:)');
% [Corrpeak.rho_pval_r(1),Corrpeak.rho_pval_r(2)] = corr(EstimatAdapt,Corrpeak.OKANR_peak(2,:)');
% 
% plot(EstimatAdapt,Corrpeak.OKANL_peak(2,:),'o',...
%     'MarkerEdgeColor','b',...
%     'MarkerSize',15,...
%     'LineWidth',2.5);
% 
% hold on
% plot(EstimatAdapt,Corrpeak.OKANR_peak(2,:),'o',...
%     'MarkerEdgeColor','r',...
%     'MarkerSize',15,...
%     'LineWidth',2.5);


%peak correlate of every sample to estimate OKN adaptation





end